# This file should not be used in deployed environments. Instead, set
# the SETTINGS_PATH environment variable to point to a configuration
# file that contains these settings.
---
defaults: &defaults
  ####################
  # GENERAL SETTINGS #
  ####################
  broker_name: interoperator-broker
  username: {{ .Values.broker.username }}
  password: {{ .Values.broker.password }}
  skip_ssl_validation: true
  log_path: /opt/service-fabrik-broker/logs/kubernetes.log
  log_level: silly
  colorize_log: false
  sys_log_level: info
  enable_circuit_breaker: true
  http_timeout: 175000
  
  ##############################
  #  DISABLED API CONTROLLERS #
  ###############################
  disabled_apis:
  - admin
  - manage
  - api  
  ##############################
  # INTERNAL ENDPOINT SETTINGS #
  ##############################
  internal: &internal
    log_event: false
    event_type: SF.BROKER_EVENT
    domain_socket:
      path: /tmp/var
      fwd_events: true
    port: 9293
    ip: 10.0.2.3
    protocol: http
    host: 10.0.2.3:9293

  ##############################
  # APISERVER SETTINGS #
  ##############################
  apiserver:
    getConfigInCluster: true
    isServiceDefinitionAvailableOnApiserver: true
    enable_namespace: true
    crds:
      "osb.servicefabrik.io_v1alpha1_sfserviceinstances.yaml": {{ (.Files.Get "conf/sfserviceinstance.yaml") | b64enc }}
      "osb.servicefabrik.io_v1alpha1_sfservicebindings.yaml": {{ (.Files.Get "conf/sfservicebinding.yaml") | b64enc }}
      "osb.servicefabrik.io_v1alpha1_sfservices.yaml": {{ (.Files.Get "conf/sfservice.yaml") | b64enc }}
      "osb.servicefabrik.io_v1alpha1_sfplans.yaml": {{ (.Files.Get "conf/sfplan.yaml") | b64enc }}
  ######################
  # APISERVER LOCK TTL #
  ######################
  lockttl:
    lifecycle: 86400 # in s(1 day)
    backup: 86400 # in s(1 days)
    restore: 86400 # in s(1 days)

  #######################
  # MONITORING SETTINGS #
  #######################
  monitoring:
    success_state: 'ok'
    success_metric: 0
    failure_state: 'critical'
    failure_metric: 1
    warning_state: 'warning'
    inprogress_state: 'in progress'
    inprogress_metric: 2
    event_name_prefix: broker.0.interoperator
    include_response_body: false
    events_logged_in_db: create_backup, update_instance
    unauthorized:
      http_status:
      - 401
      - 403
      event_name: 'unauthorized_access'
      description: 'Unauthorized access to service attempted'
      tags:
      - security
      - unauthorized
      include_response_body: true

  ###################
  # QUOTA MANAGEMENT SETTINGS #
  ###################
  quota:
    enabled: {{ .Values.broker.quota.enabled }}
    oauthDomain: {{ .Values.broker.quota.oauthDomain }}
    serviceDomain: {{ .Values.broker.quota.serviceDomain }}
    username: {{ .Values.broker.quota.username }}
    password: {{ .Values.broker.quota.password }}

development: &development
  <<: *defaults
  log_level: debug

kubernetes:
  <<: *development
  log_level: debug
