azs:
- name: z1
  cloud_properties:
    availability_zone: z1
- name: z2
  cloud_properties:
    availability_zone: z2
- name: z3
  cloud_properties:
    availability_zone: z3
compilation:
  network: compilation_network
  reuse_compilation_vms: true
  vm_type: minimal
  workers: 6
disk_types:
- disk_size: 1024
  name: 1GB
- disk_size: 5120
  name: 5GB
- disk_size: 10240
  name: 10GB
- disk_size: 100240
  name: 100GB
- disk_size: 1024
  name: default
networks:
- name: compilation_network
  type: dynamic
- name: default
  subnets:
  - azs:
    - z1
    - z2
    - z3
    cloud_properties:
      name: random
    gateway: 10.244.0.1
    range: 10.244.0.0/20
    reserved:
    - 10.244.0.1
    static:
    - 10.244.0.2 - 10.244.15.254
vm_extensions:
- name: 5GB_ephemeral_disk
- name: 10GB_ephemeral_disk
- name: 50GB_ephemeral_disk
- name: 100GB_ephemeral_disk
- name: 500GB_ephemeral_disk
- name: 1TB_ephemeral_disk
- cloud_properties:
    ports:
    - host: 80
    - host: 443
    - host: 2222
  name: ssh-proxy-and-router-lb
- cloud_properties:
    ports:
    - host: 1024-1123
  name: cf-tcp-router-network-properties
- cloud_properties:
    ports:
    - host: 8845
  name: credhub-lb
vm_types:
- name: minimal
- name: small
- name: small-highmem
- name: default
